language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux
  - osx
before_script:
  - chmod 755 ./bin/swagger-builder.js
  - yarn
  - yarn test-yaml
  - yarn test-json
  - yarn babel
script: 
  - yarn lint
  - yarn test
jobs:
  include:
    - name: Browser tests (Linux)
      os: linux
      script: yarn test-yaml
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Mac)
      os: osx
      script: yarn test-yaml
      addons:
        firefox: latest
        chrome: stable

